## Arquivo de compose do Jenkins, voce deve alterar o caminho "/home/ec2-user/jenkins" no campo "volumes:" caso a pasta "/home/ec2-user/" não exista 

version: '2.0'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 80:8080
    volumes: 
      - /home/ec2-user/jenkins/:/var/jenkins_home/ , rw 
