pipeline {
    agent { 
        docker {
            image 'maven:2'
            args '-v /var/run/docker.sock:/var/run/docker.sock --user=root'
        }
    }            
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                sh '''
                git clone --branch develop https://github.com/frovai/poc-teste.git
                '''
            }
        }
        stage('Maven Install') {
            steps {
                sh '''
                cd poc-teste/terraform-files/spring-boot-dockerize/
                mvn compile
                mvn install
                '''
            }
        }
        stage('Maven Test') {
            steps {
                sh '''
                cd poc-teste/terraform-files/spring-boot-dockerize/
                mvn test
                '''
            }
        } 
        //stage('INFRA - TESTE') {
        //    steps {
        //        sh '''
        //        '''
        //    }
        //}    
        stage('Maven Deploy Artifact') {
            steps {
            withCredentials([sshUserPrivateKey(credentialsId: 'DEPLOY_KEY', keyFileVariable: 'DEPLOY_KEY')]) {
                sh '''
                cd poc-teste/terraform-files/spring-boot-dockerize/target
                scp -i ${DEPLOY_KEY} -o StrictHostKeyChecking=no spring-boot-docker.jar ec2-user@${SPRING_SERVER}:/home/ec2-user/poc-teste/terraform-files/spring-boot-dockerize/target
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml down"
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml build --no-cache"
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml up -d"
                sleep 90
                scp -i ${DEPLOY_KEY} -o StrictHostKeyChecking=no spring-boot-docker.jar ec2-user@${SPRING_SERVER2}:/home/ec2-user/poc-teste/terraform-files/spring-boot-dockerize/target
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER2} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml down"
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER2} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml build --no-cache"
                ssh -o StrictHostKeyChecking=no -i ${DEPLOY_KEY} ec2-user@${SPRING_SERVER2} "sudo /usr/bin/docker-compose -f /home/ec2-user/spring.yml up -d"
                '''
                }
            }
        }        
    }
}
