version: '2.0'

services:

  jenkins:
    build:
       dockerfile: Dockerfile-jenkins-docker-in-docker
       context: ./
    image: jenkins/poc:1
    container_name: jenkins
    restart: always
    ports:
      - 80:8080
    volumes:
      - /home/ec2-user/jenkins/:/var/jenkins_home/ , rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
