FROM openjdk:8
EXPOSE 8080
ADD https://github.com/frovai/poc-teste/blob/teste-elb/terraform-files/spring-boot-dockerize/target/spring-boot-docker.jar  spring-boot-docker.jar 
ENTRYPOINT ["java","-jar","/spring-boot-docker.jar"]
